name: 'Github Release Limiter'
description: 'Github action to limit the number of releases in a repo'
author: 'Corrine Olson'
inputs:
  myToken:
    description: this should be a token with access to your repository scoped in as a secret
    required: true
  maxReleases:
    description: maximum number of releases allowed in repo
    required: true
  deleteTags:
    description: whether to delete tags associated to releases
    required: false
    default: false

runs:
  using: 'node16'
  main: 'dist/index.js'
